apiVersion: v1
kind: Secret
metadata:
  name: banxia-secrets
  namespace: banxia
type: Opaque
stringData:
  POSTGRES_DB: banxia
  POSTGRES_USER: banxia
  POSTGRES_PASSWORD: REPLACE_WITH_POSTGRES_PASSWORD
  CLICKHOUSE_DB: banxia
  CLICKHOUSE_USER: banxia
  CLICKHOUSE_PASSWORD: REPLACE_WITH_CLICKHOUSE_PASSWORD
  REDIS_PASSWORD: REPLACE_WITH_REDIS_PASSWORD
  MINIO_ROOT_USER: banxia
  MINIO_ROOT_PASSWORD: REPLACE_WITH_MINIO_PASSWORD
  BANXIA_POSTGRES_DSN: postgresql://banxia:REPLACE_WITH_URL_ENCODED_POSTGRES_PASSWORD@postgres:5432/banxia
  BANXIA_CLICKHOUSE_PASSWORD: REPLACE_WITH_CLICKHOUSE_PASSWORD
  BANXIA_REDIS_URL: redis://:REPLACE_WITH_URL_ENCODED_REDIS_PASSWORD@redis:6379/0
  BANXIA_MINIO_ACCESS_KEY: banxia
  BANXIA_MINIO_SECRET_KEY: REPLACE_WITH_MINIO_PASSWORD
  BANXIA_API_TOKEN: REPLACE_WITH_RANDOM_API_TOKEN
  BANXIA_CODE_COMMIT: REPLACE_WITH_GIT_COMMIT
---
apiVersion: v1
kind: Secret
metadata:
  name: banxia-registry
  namespace: banxia
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "REPLACE_WITH_CR_REGISTRY": {
          "username": "REPLACE_WITH_CR_USERNAME",
          "password": "REPLACE_WITH_CR_PASSWORD",
          "auth": "REPLACE_WITH_BASE64_USERNAME_COLON_PASSWORD"
        }
      }
    }
