- op: add
  path: /spec/template/spec/nodeSelector
  value:
    kubernetes.io/os: linux
- op: add
  path: /spec/template/spec/serviceAccountName
  value: banxia-workload
- op: add
  path: /spec/template/spec/automountServiceAccountToken
  value: false
- op: add
  path: /spec/template/spec/topologySpreadConstraints
  value:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchExpressions:
          - key: app
            operator: Exists
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchExpressions:
          - key: app
            operator: Exists
