apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: banxia-ebs-retain
provisioner: ebs.csi.volcengine.com
parameters:
  ChargeType: PostPaid
  projectName: default
  type: ESSD_PL0
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: banxia-nas-rwx
provisioner: nas.csi.volcengine.com
parameters:
  fsId: enas-cnsha08273a84410dd
  server: cnsha08273a84410dd.vpc-1pm13zlt8zq4g643rfzcpm2z8.nas.ivolces.com
  fsType: nfs
  volumeAs: subpath
  subPath: /banxia/reports
  archiveOnDelete: "true"
mountOptions:
  - nolock
  - proto=tcp
  - noresvport
  - vers=3
reclaimPolicy: Retain
allowVolumeExpansion: true
volumeBindingMode: Immediate
